import Head from "next/head";
import { Box } from "@chakra-ui/react";

import Header from "../components/Header";
import Footer from "../components/Footer";
import Search from "../components/Search";

export default function Home() {
  return (
    <Box h="100vh" w="100ww">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box
        as="main"
        d="flex"
        justifyContent="center"
        h="70vh"
        bgColor="#f0f5f1"
        w="100vw"
      >
        <Search />
      </Box>
      <Footer />
    </Box>
  );
}
